### ISSUE TITLE
Server Error when requesting incorrect format for vocabulary file

### ISSUE THREAD

**Issue by somexpert** [unt-libraries/django-controlled-vocabularies#23]
So currently a request that looks like this:
`/[vocab_name]/[something outside of JSON, XML, TKL, or PY]`
such as `/institutions/THE` raises a server error stemming from an unbound local error on `vocabulary_object` because we don't hit any of [these conditionals.](https://github.com/unt-libraries/django-controlled-vocabularies/blob/master/controlled_vocabularies/views.py#L109)
Simple solutions: either provide an `else` clause in the view or limit the URL regex to only accept those chosen strings.

**Comment by ldko** [comment]
Personally, since it is part of the actual URL vs a query parameter, I would raise a `404`--perhaps via an `else` rather than the URL regex, but I could be easily swayed on this.

**Comment by somexpert** [comment]
The `else` makes sense, that way we don't have to update two places if we add/remove formats.
