### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by krzysztofjeziorny** [unt-libraries/django-controlled-vocabularies#45]
Hi,
I stumbled upon your package and love to use it, as yours is Django 4.2-compatible. 
However, I cannot install it with the recommended command `pip install git+git://github.com/unt-libraries/django-controlled-vocabularies.git`

pip 23.2.1
python 3.11.5
Django 4.2.5
git 2.42.0, 2.39.2
os MacOS 13.6, Debian 12.1
shell zsh, fish

Output from MacOS, same goes for Debian:

```bash
.venv ❯ pip install git+git://github.com/unt-libraries/django-controlled-vocabularies.git
Collecting git+git://github.com/unt-libraries/django-controlled-vocabularies.git
  Cloning git://github.com/unt-libraries/django-controlled-vocabularies.git to /private/var/folders/y6/v8zpdv9n7qb4np29ywcd_m9r0000gn/T/pip-req-build-ohnzd982
  Running command git clone --filter=blob:none --quiet git://github.com/unt-libraries/django-controlled-vocabularies.git /private/var/folders/y6/v8zpdv9n7qb4np29ywcd_m9r0000gn/T/pip-req-build-ohnzd982
  fatal: unable to connect to github.com:
  github.com[0: 140.82.121.3]: errno=Operation timed out

  error: subprocess-exited-with-error

  × git clone --filter=blob:none --quiet git://github.com/unt-libraries/django-controlled-vocabularies.git /private/var/folders/y6/v8zpdv9n7qb4np29ywcd_m9r0000gn/T/pip-req-build-ohnzd982 did not run successfully.
  │ exit code: 128
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --filter=blob:none --quiet git://github.com/unt-libraries/django-controlled-vocabularies.git /private/var/folders/y6/v8zpdv9n7qb4np29ywcd_m9r0000gn/T/pip-req-build-ohnzd982 did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

My SSH keys for GitHub are all right. It may be my specific problem, but I was wondering if you can reproduce it.

**Comment by somexpert** [comment]
I believe what you want to use to install with ssh is this:
`pip install git+ssh://git@github.com/unt-libraries/django-controlled-vocabularies`

or, for https:
`pip install git+https://github.com/unt-libraries/django-controlled-vocabularies`

Those both worked for me. Hopefully that will resolve the issue for you!

**Comment by somexpert** [comment]
Ah, I see that we've recommended that command in the README. I will correct that now. Thanks for pointing it out!

**Comment by somexpert** [comment]
I've adjusted the README to fix the installation instructions and add some other potentially helpful instructions in the two commits below:
950bb17be5b17bc673176bfb24c2149105f22da8
6bec399c978d196800b131159dd07280f286fc16

Once again, thank you for bringing this issue to our attention!

**Comment by krzysztofjeziorny** [comment]
Oh, I also didn't catch the protocol error! Thanks for that.

One question still, the package `5.0.0` installed with this method has requirement of `lxml==4.9.1`, even if the file [requirements-common.txt](https://github.com/unt-libraries/django-controlled-vocabularies/blob/6bec399c978d196800b131159dd07280f286fc16/requirements/requirements-common.txt#L1C3-L1C3) is more loose with the version using `~=`. lxml is at 4.9.3 at this point already.

**Comment by somexpert** [comment]
Ah, looks like that was an oversight, but I've adjusted it now in setup.py to match what we have in requirements-common.py:
3ab0013d487550f9cca5ac3ffce7332d3f8d40e1
