### ISSUE TITLE
Verbose vocabularies view orders terms incorrectly

### ISSUE THREAD

**Issue by somexpert** [unt-libraries/django-controlled-vocabularies#5]
The view tries to order the terms based on a non-existent order field in linked vocabulary. The order field is in the term object, not the linked vocabulary object.

**Comment by ldko** [comment]
The Vocabulary field does have an order field, and on looking at #9, I think this was correct before the change. Terms should be ordered by the field named in the value of `order` of the vocabulary to which they belong, so I think vocab.order was correct.
