### ISSUE TITLE
Re-evaluate requirements files

### ISSUE THREAD

**Issue by damonkelley** [unt-libraries/django-controlled-vocabularies#6]
As it stands currently, we have two requirements files.
- `requirements.txt` - which houses the requirements to for working on the application
- `requirementst-test.txt` - which houses the requirements for testing the application, sans Django, as it is expected to be installed via tox.

The issue is that there is not a single file to begin all development activities. As a developer, you must install both `requirements.txt` and `requirements-test.txt` in order to run the tests and work on the app. Furthermore, we also have overlapping dependencies, namely `lxml`.

Here are some examples:
#### Scenario 1
- clone
- `pip install -r requirements.txt`
- `./runtests.py`

**Outcome**: Fails because test requirments are not installed.

#### Scenario 2
- clone
- `pip install -r requirements-test.txt`
- `./runtests.py`

**Outcome**: Fails because Django is not installed.

**Comment by somexpert** [comment]
This was fixed with the initial release.
